name: Scala CI

on:
  push:
    branches: ["master", "beta"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "sbt"
      - name: Run compile
        run: sbt compile
      - name: Run tests
        run: sbt clean coverage test
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3
